# Generated by Django 2.2.13 on 2025-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_articlepost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='editor_type',
            field=models.CharField(default='markdown', max_length=1500),
        ),
    ]
