# Generated by Django 2.2.13 on 2025-04-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_articlepost_editor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='editor_type',
            field=models.CharField(default='ckeditor', max_length=1500),
        ),
    ]
