# Generated by Django 2.2.28 on 2025-04-21 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20250419_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
