# Generated by Django 2.2.28 on 2025-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20250421_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='是否草稿'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
